apiVersion: 1

datasources:
  - name: ReDB-Prometheus
    uid: redb-prometheus
    type: prometheus
    access: proxy
    url: http://localhost:8080
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: GET
