apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://127.0.0.1:8428
    uid: victoriametrics
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 10s
      queryTimeout: 30s
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      manageAlerts: false
